/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektbiblioteka;

/**
 *
 * @author B.Grzadzielewski
 */
import java.sql.ResultSet;
import model.Czytelnik;
import model.Ksiazka;
import model.Wypozyczenie;
import model.Miasta;
import model.MyTableModel;
import Biblioteka.Biblioteka;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import static java.util.Collections.list;
import java.util.List;
import java.util.Scanner;
import static javafx.beans.binding.Bindings.select;
import javax.swing.DefaultComboBoxModel;
import javax.swing.RowFilter;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import static model.Password.*;

public class BibliotekaApp extends javax.swing.JFrame {
    
    File plik = new File("lang.txt");
    Biblioteka b = new Biblioteka();
    static String [] language = new String[] {"polska", "Córdoba", "La Plata"}; 
    DefaultTableModel model = new DefaultTableModel(new Object[][] {},
     new Object[] { language[0], "Imie","Nazwisko", "Pesel", "DOB", "Uźytkownik", "email", "Adres", "Telefon"});

   
    
     
        static String [] language_polski = {"polska", "Córdoba", "La Plata"};
        static String [] language_angielski = {"anglia", "Córdoba", "La Plata"};
   
    static void jezyk() throws FileNotFoundException{
        Scanner odczyt = new Scanner(new File("lang.txt"));
        String text = "pol";
        text = odczyt.nextLine();
        System.out.println(text);
        Arrays.fill (language, null);
        if (text.equals("ang")) language = language_angielski.clone();
        else language = language_polski.clone();
        System.out.println(language[0]);
    }    
    
    DefaultComboBoxModel modelbox = new DefaultComboBoxModel<>(new String[] {"Inne" });
 
    
    public void listadd() {
        List<Czytelnik> czytelnicy;
         czytelnicy=b.selectCzytelnicy();
         modelbox.addElement(czytelnicy.get(0).getImie()+"  "+czytelnicy.get(0).getNazwisko());
         modelbox.addElement(czytelnicy.get(1).getImie()+"  "+czytelnicy.get(1).getNazwisko());
         modelbox.addElement(czytelnicy.get(2).getImie()+"  "+czytelnicy.get(2).getNazwisko());
    }
    
    /*
    public String[][] ListToArr(List<Czytelnik> czytelnicy) {
        int dl= czytelnicy.size();
        
        String [][] czyt = new String[dl][4];
        for (int i=0; i<dl; i++)
        {
            String tmp=String.format("%06d",czytelnicy.get(i).getId() );
            czyt[i][0]=tmp;
            czyt[i][1]=czytelnicy.get(i).getImie();
            czyt[i][2]=czytelnicy.get(i).getNazwisko();
            czyt[i][3]=czytelnicy.get(i).getPesel();
        }
        return czyt;
    }
    */
    
    void SelectCzytelnicyToTable(String[][] tab) {
         model.setRowCount(0);
         for (int i=0; i<tab.length; i++)
           model.addRow(tab[i]);
    }
    
    
    public BibliotekaApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknotest = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        zakladki = new javax.swing.JTabbedPane();
        ZakladkaCzytelnicy = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaCzytelnicy = new javax.swing.JTable(model);
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        IDfield = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        filtr_ID = new javax.swing.JTextField();
        filtr_ID1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        ZakladkaKsiazki = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>(modelbox);
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel2.setText(language[0]);

        javax.swing.GroupLayout oknotestLayout = new javax.swing.GroupLayout(oknotest.getContentPane());
        oknotest.getContentPane().setLayout(oknotestLayout);
        oknotestLayout.setHorizontalGroup(
            oknotestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknotestLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel2)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        oknotestLayout.setVerticalGroup(
            oknotestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknotestLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        zakladki.setBackground(new java.awt.Color(204, 255, 204));
        zakladki.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ZakladkaCzytelnicy.setBackground(new java.awt.Color(255, 255, 204));
        ZakladkaCzytelnicy.setAlignmentX(0.0F);
        ZakladkaCzytelnicy.setAlignmentY(0.0F);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setMaximumSize(new java.awt.Dimension(820, 320));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(820, 320));
        jScrollPane3.setVerticalScrollBarPolicy(jScrollPane3.VERTICAL_SCROLLBAR_ALWAYS);
        //jScrollPane3.setVerticalScrollBar(verticalScrollBar);

        TabelaCzytelnicy.setAutoCreateRowSorter(true);
        TabelaCzytelnicy.getColumnModel().getColumn(0).setPreferredWidth(60);
        TabelaCzytelnicy.getColumnModel().getColumn(1).setPreferredWidth(100);
        TabelaCzytelnicy.getColumnModel().getColumn(2).setPreferredWidth(110);
        TabelaCzytelnicy.getColumnModel().getColumn(3).setPreferredWidth(85);
        TabelaCzytelnicy.getColumnModel().getColumn(4).setPreferredWidth(80);
        TabelaCzytelnicy.getColumnModel().getColumn(5).setPreferredWidth(100);
        TabelaCzytelnicy.getColumnModel().getColumn(6).setPreferredWidth(110);
        TabelaCzytelnicy.getColumnModel().getColumn(7).setPreferredWidth(200);
        TabelaCzytelnicy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaCzytelnicy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TabelaCzytelnicy.setModel(model);
        TabelaCzytelnicy.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        TabelaCzytelnicy.setMaximumSize(new java.awt.Dimension(800, 300));
        TabelaCzytelnicy.setMinimumSize(new java.awt.Dimension(800, 300));
        TabelaCzytelnicy.setName(""); // NOI18N
        TabelaCzytelnicy.setRowHeight(24);
        TabelaCzytelnicy.getTableHeader().setReorderingAllowed(false);
        TabelaCzytelnicy.getTableHeader().setResizingAllowed(false);
        TabelaCzytelnicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaCzytelnicyMousePressed(evt);
            }
        });
        TabelaCzytelnicy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelaCzytelnicyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaCzytelnicyKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaCzytelnicy);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        IDfield.setText("ID");

        jButton4.setText("USUN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("dodaj ksiazke");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("pokaz joina");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        filtr_ID.setText("ID czyt");
        filtr_ID.setAlignmentX(0.0F);
        filtr_ID.setAlignmentY(0.0F);
        filtr_ID.setAutoscrolls(false);
        filtr_ID.setMargin(new java.awt.Insets(2, 0, 0, 0));
        filtr_ID.setMaximumSize(new java.awt.Dimension(70, 25));
        filtr_ID.setMinimumSize(new java.awt.Dimension(70, 25));
        filtr_ID.setName(""); // NOI18N
        filtr_ID.setPreferredSize(new java.awt.Dimension(70, 30));
        filtr_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                filtr_IDFocusGained(evt);
            }
        });
        filtr_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtr_IDActionPerformed(evt);
            }
        });

        filtr_ID1.setText("imie");
        filtr_ID1.setAlignmentX(0.0F);
        filtr_ID1.setAlignmentY(0.0F);
        filtr_ID1.setAutoscrolls(false);
        filtr_ID1.setMargin(new java.awt.Insets(2, 0, 0, 0));
        filtr_ID1.setMaximumSize(new java.awt.Dimension(70, 25));
        filtr_ID1.setMinimumSize(new java.awt.Dimension(70, 25));
        filtr_ID1.setName(""); // NOI18N
        filtr_ID1.setPreferredSize(new java.awt.Dimension(70, 30));

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ZakladkaCzytelnicyLayout = new javax.swing.GroupLayout(ZakladkaCzytelnicy);
        ZakladkaCzytelnicy.setLayout(ZakladkaCzytelnicyLayout);
        ZakladkaCzytelnicyLayout.setHorizontalGroup(
            ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZakladkaCzytelnicyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(40, 40, 40)
                .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(56, 56, 56))
            .addGroup(ZakladkaCzytelnicyLayout.createSequentialGroup()
                .addGroup(ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZakladkaCzytelnicyLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton8)
                        .addGap(30, 30, 30)
                        .addComponent(jButton9))
                    .addGroup(ZakladkaCzytelnicyLayout.createSequentialGroup()
                        .addComponent(filtr_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(filtr_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(403, Short.MAX_VALUE))
            .addGroup(ZakladkaCzytelnicyLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                .addContainerGap())
        );
        ZakladkaCzytelnicyLayout.setVerticalGroup(
            ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZakladkaCzytelnicyLayout.createSequentialGroup()
                .addGroup(ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZakladkaCzytelnicyLayout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addGroup(ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(ZakladkaCzytelnicyLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtr_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtr_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ZakladkaCzytelnicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(26, 26, 26))
        );

        zakladki.addTab("Czytelnicy", ZakladkaCzytelnicy);

        jComboBox1.setEditable(true);
        /*
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Inne" }));
        */
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ZakladkaKsiazkiLayout = new javax.swing.GroupLayout(ZakladkaKsiazki);
        ZakladkaKsiazki.setLayout(ZakladkaKsiazkiLayout);
        ZakladkaKsiazkiLayout.setHorizontalGroup(
            ZakladkaKsiazkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZakladkaKsiazkiLayout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton7)
                .addGap(337, 337, 337))
        );
        ZakladkaKsiazkiLayout.setVerticalGroup(
            ZakladkaKsiazkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZakladkaKsiazkiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ZakladkaKsiazkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        zakladki.addTab("Książki", ZakladkaKsiazki);

        jLabel1.setText("Użytkownik: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zakladki, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(zakladki, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        zakladki.getAccessibleContext().setAccessibleName("Czytelnicy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       SelectCzytelnicyToTable(b.selectCzytelnicyZAdresem());
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        b.updateCzytelnikImie("AHMED", 4);
        //SelectCzytelnicyToTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TabelaCzytelnicyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaCzytelnicyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("WYWOLANIE");
                int row = TabelaCzytelnicy.getSelectedRow();
                int column = TabelaCzytelnicy.getSelectedColumn();

                // resul is the new value to insert in the DB
                String resul = TabelaCzytelnicy.getValueAt(row, column).toString();
                // id is the primary key of my DB
                String id = TabelaCzytelnicy.getValueAt(row, 0).toString();
                b.updateCzytelnik(id,resul,column);}
        //else if (evt.getKeyCode() == KeyEvent.VK_UP) {int row = jTable2.getSelectedRow();
         //String tmp = jTable2.getValueAt(row, 0).toString();
        //IDfield.setText(tmp);}
    }//GEN-LAST:event_TabelaCzytelnicyKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        b.insertCzytelnik("Maria", "Kiszka", "734873487324");
        System.out.println("Dodano Czytelnika");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        b.DeleteCzytelnikId(IDfield.getText());
        System.out.println("USUNIETO CZYTELNIKA");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        b.insertKsiazka("jakistytul", "jakisautor", "przygoda");
        b.insertWypozycz(1, 1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       List<Ksiazka> ksiazki = b.selectKsiazki();
        System.out.println("Lista książek:");
       for(Ksiazka k: ksiazki)
        System.out.println(k);
       
     //  List<jointest> join = b.selectJoin();
      // System.out.println("Join");
      // for(jointest k: join)
      //  System.out.println(k);
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TabelaCzytelnicyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCzytelnicyMousePressed
         int row = TabelaCzytelnicy.getSelectedRow();
         String tmp = TabelaCzytelnicy.getValueAt(row, 0).toString();
        IDfield.setText(tmp);
    }//GEN-LAST:event_TabelaCzytelnicyMousePressed

    private void TabelaCzytelnicyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaCzytelnicyKeyReleased
        if ((evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN) ) 
        {int row = TabelaCzytelnicy.getSelectedRow();
         String tmp = TabelaCzytelnicy.getValueAt(row, 0).toString();
        IDfield.setText(tmp);}
    }//GEN-LAST:event_TabelaCzytelnicyKeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        listadd();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void filtr_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtr_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtr_IDActionPerformed

    private void filtr_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filtr_IDFocusGained
        filtr_ID.selectAll();
    }//GEN-LAST:event_filtr_IDFocusGained

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Arrays.fill (language, null);
        //language = language_angielski.clone();
        //System.out.println(language[0]);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        oknotest.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotekaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotekaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotekaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotekaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //Biblioteka b = new Biblioteka();
        
         
        
        jezyk();
      
        
        // DefaultTableModel model = new DefaultTableModel(new Object[][] {},
        // new Object[] { language[0], "Imie","Nazwisko", "Pesel", "DOB", "Uźytkownik", "email", "Adres", "Telefon"});
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotekaApp().setVisible(true);
            }
        });
       //List<Czytelnik> czytelnicy;
       // czytelnicy = b.selectCzytelnicy();
        //System.out.println("Wyswietl liste 'czytelnicy'");
        // for(Czytelnik c: czytelnicy)
        //    if (c.getImie().equalsIgnoreCase("karol"))    
            //   System.out.println(c);
       //  System.out.println("----------------------");
        // int rozmiar=czytelnicy.size();
       // for (int i=0; i<rozmiar; i++)
           //czytelnicy.remove(0);
        
         //for(Czytelnik c: czytelnicy)
        //    if (c.getImie().equalsIgnoreCase("karol"))    
            //   System.out.println(c);
         
         // System.out.println("----------------------");
                  
        
        
        
      //  System.out.println("----------------------");
       // b.CzytelnikImie("Karol", czytelnicy);
       // System.out.println("----------------------");
        
        //for(Czytelnik c: czytelnicyImie)
        //    if (c.getImie().equalsIgnoreCase("karol"))    
             //  System.out.println(c);

       //System.out.println("Lista książek:");
       //for(Ksiazka k: ksiazki)
        //System.out.println(k);
        
        
        //System.out.println(czytelnicy.get(0).getImie());
      //  List<Czytelnik> czytelnicyByName;
       // czytelnicyByName=b.selectCzytelnicyByName("Karolina");
       // System.out.println("Wyswietl liste 'czytelnicyByName'");
        //for(Czytelnik c: czytelnicyByName)
        //    if (c.getImie().equalsIgnoreCase("karol"))    
              // System.out.println(c);

              String haslo = "Mlotek66";
              String hash = "";
              hash=hashPassword(haslo);
              System.out.println(haslo);
              System.out.println(hash);
              System.out.println(checkPassword("Mlotek66","$2a$12$P65cxIwXnqiQiXpuhg9EnOURw4IFeDuLvhD94ObqStAouaC4UcBJi"));
              
        String jeden = "1";
        String dwa = "dwanapis";
        List <String>lista1 = new ArrayList();
        lista1.add(jeden);
        lista1.add(dwa);
        
        System.out.println(lista1);
    
       
              

       // b.closeConnection(); 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDfield;
    private javax.swing.JTable TabelaCzytelnicy;
    private javax.swing.JPanel ZakladkaCzytelnicy;
    private javax.swing.JPanel ZakladkaKsiazki;
    private javax.swing.JTextField filtr_ID;
    private javax.swing.JTextField filtr_ID1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JFrame oknotest;
    private javax.swing.JTabbedPane zakladki;
    // End of variables declaration//GEN-END:variables
}
